sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 50
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 51
      end: 89
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 90
      end: 124
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 125
      end: 189
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 190
      end: 235
      scaling: 0.6
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 236
      end: 297
      scaling: 0.7
      only_FTG: false
      no_FTG: false
